name: indr_agri
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.7
  cupertino_icons: ^1.0.0
  dartz: ^0.9.1
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.5
  flutter_hooks: ^0.14.0
  freezed_annotation: ^0.11.0+1
  get_it: ^4.0.4
  google_sign_in: ^4.5.3
  injectable: ^1.0.4
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  rxdart: ^0.24.1
  uuid: ^2.2.2
  webview_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: null
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.11.6
  injectable_generator: ^1.0.4
  json_serializable: ^3.4.1
  lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/leaf.png
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf

flutter_icons:
  image_path: 'assets/images/leaf.png'
  android: true
  ios: true