name: indr_agri
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^1.0.2
  cloud_firestore: ^1.0.2
  cupertino_icons: ^1.0.2
  dartz: 0.10.0-nullsafety.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  fl_chart: ^0.36.0
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.16.0
  flutter_native_splash: ^1.1.8+4
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0
  google_sign_in: ^5.0.1
  injectable: ^1.2.2
  json_annotation: ^4.0.1
  kt_dart: ^0.9.0
  rxdart: ^0.26.0
  uuid: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^1.0.2
  build_runner: null
  flutter_launcher_icons: ^0.9.0
  freezed: ^0.14.1+1
  injectable_generator: ^1.2.2
  json_serializable: ^4.1.0
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/leaf.png
    - assets/images/indr_agri.jpg
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf

flutter_icons:
  image_path: 'assets/images/leaf.png'
  android: true
  ios: true
